/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActivityItem: typeof import('./src/components/user/ActivityItem.vue')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    CircleItem: typeof import('./src/components/user/CircleItem.vue')['default']
    CollectionItem: typeof import('./src/components/user/CollectionItem.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GoogleSignIn: typeof import('./src/components/GoogleSignIn.vue')['default']
    LoadingBar: typeof import('./src/components/LoadingBar.vue')['default']
    NewsSection: typeof import('./src/components/NewsSection.vue')['default']
    PostItem: typeof import('./src/components/user/PostItem.vue')['default']
    PublishButton: typeof import('./src/components/PublishButton.vue')['default']
    QRCodeImage: typeof import('./src/components/QRCodeImage.vue')['default']
    RightSideTools: typeof import('./src/components/layout/RightSideTools.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceFields: typeof import('./src/components/publish/ServiceFields.vue')['default']
    ServiceItem: typeof import('./src/components/user/ServiceItem.vue')['default']
    SideNavigation: typeof import('./src/components/layout/SideNavigation.vue')['default']
    TopBanner: typeof import('./src/components/TopBanner.vue')['default']
    UserItem: typeof import('./src/components/user/UserItem.vue')['default']
    WeChatLogin: typeof import('./src/components/WeChatLogin.vue')['default']
  }
}
